### ISSUE TITLE
endwalker update

### ISSUE THREAD

**Issue by LastExceed** [NightmareXIV/SelectString#1]
any chance to get this updated for endwalker? this sounds super useful

**Comment by Limiana** [comment]
not as useful anymore I'm afraid due to aethernet changes, I do plan a complete overhaul of this plugin eventually, but that'll have to be like, after savage most likely or even after ultimate.

In meantime though I'll update what I have already, In some reasonable amount of time (until end of this week likely). Been a bit lazy about it because of queues that limit possibility of plugin testing quite a bit

**Comment by str0mback** [comment]
Would love to see this getting some love, was really useful when going through retainers. <3

**Comment by Limiana** [comment]
Hello!
I'll update it as soon as I can find time for it, been really busy lately

**Comment by Limiana** [comment]
Updated now, should work fine. Apologies, had really busy time lately.
